### ISSUE TITLE
Bug: <br />

### ISSUE THREAD

**Issue by shshaw** [shshaw/Splitting#10]
Issue with `<br />` causing words after to not be split.

https://codepen.io/shshaw/pen/b97ceab839601bf0a1ac395c41488ca8

**Comment by notoriousb1t** [comment]
Taking a quick peek at this, I think the problem is in the splitText function.  we are using el.childNodes.forEach which is a live list.  I think because <br/> is being removed and added to the document fragment, it is shorting the childNodes list and so the text node at the end does not get called.

We might be able to solve this by changing the line to

```js
$(el.childNodes).forEach
```

**Comment by shshaw** [comment]
Yeah, something like `$(el.childNodes)` is what I originally used.

Also: keep in mind that NodeList.forEach isn't supported outside of very
recent browsers. Need to convert to Array with our $ function before any
looping like that :-)

**Comment by notoriousb1t** [comment]
Yes we should add it for that alone.  I had forgotten that IE doesn't have NodeList.forEach.

**Comment by notoriousb1t** [comment]
It required a little more work than just $().  I believe I have mixed content working properly for splitting words.  All empty elements are preserved, so that Are We Good demo, should work now.

Reference: https://github.com/shshaw/Splitting/commit/b730ef8fbc1b70a5190ebf1ce4a8664df7567038

Want to take it for a spin?

**Comment by shshaw** [comment]
Looks like it works to me for <br /> but there seems to be an issue with a lack of spacing between a new element (see the <a>)
https://codepen.io/shshaw/pen/b97ceab839601bf0a1ac395c41488ca8

**Comment by notoriousb1t** [comment]
I think this is something separate.  The issue appears to be that we are doing a trim before splitting the text node and then that space is not being added back into the node list:

https://github.com/shshaw/Splitting/blob/1.0.0/src/utils/split-text.js#L41

**Comment by notoriousb1t** [comment]
Alright, created https://github.com/shshaw/Splitting/issues/13
