### ISSUE TITLE
Having issue with react app 

### ISSUE THREAD

**Issue by polymer940c** [shshaw/Splitting#26]
https://codesandbox.io/s/94z5281w14
`Cannot read property 'depends' of undefined`
Maybe I'm setting it up wrong but this is the error I'm seeing. Also try doing it with the CDN, with the same error occurring.

**Comment by shshaw** [comment]
It looks like React is setting `data-splitting` to `data-splitting="true"` instead of leaving it as only the attribute as you have in the JSX. Splitting then looks for a `"true"` split plugin, which doesn't exist, hence the error! 😀 

There should be some better error checking in the plugin detection, which we'll look at for the next release.

In the meantime, the easiest fix here is to update the JSX to `<div data-splitting="">Hello World!</div>` so that it doesn't inject `true`. Alternatively, you can set exactly which split you want to use in the data attribute ( `<div data-splitting="chars">Hello World!</div>` ) or in your main Splitting call ( `Splitting({ by: 'chars' });` ). I've tested all of these, and they work in your demo.

You may also want to look at utilizing [`Splitting.html()`](https://splitting.js.org/guide.html#splitting-html) in your JSX, which will split the text before it even hits the DOM.
